export type { Article, ArticleSchema } from './model/types/article.types'
export { articleReducer } from './model/slice/article-slice'
export { fetchArticleById } from './model/services/fetch-article-by-id/fetch-article-by-id'
export { ArticleInfo } from './ui/article-info/article-info'
export { getArticleState } from './model/selectors/get-article-state'
export { ArticleView, ArticleType } from './model/constants/article.constants'
export { ArticleList } from './ui/article-list'
export type { ArticlesRecommendationSchema } from './model/types/articles-recommendation.types'
export { articlesRecommendationReducer } from './model/slice/articles-recommendation-slice'
export { getArticlesRecommendationState } from './model/selectors/get-articles-recommendation-state'
export { fetchArticlesRecommendationById } from './model/services/fetch-articles-recommendation-by-id/fetch-articles-recommendation-by-id'
export type { ArticlePageSchema } from './model/types'
export { articlePageReducer } from './model/slice'
